title: David Weon - DS Portfolio
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my portfolio of data science projects!
  Each post will outline a project that I worked on with access to the underlying data analysis.
permalink: ":title/"
baseurl: "" # the subpath of your site, e.g. /blog
url: "eunchanity.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: David Weon # add your name
author-img: david-weon.jpeg # add your photo
about-author: A data scientist who loves solving problems and the creative process to get there # add description
# social-twitter: # add your Twitter handle
# social-facebook: # add your Facebook handle
social-github: eunchanity # add your Github handle
social-linkedin: davideweon #add your Linkedin handle
social-email: davideweon@gmail.com # add your Email address

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
