# Permalinks
permalink:           pretty

# Setup
title:               David Weon
tagline:             A Data Enthusiast's Data Science Blog
url:                 http://eunchanity.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              David Weon
  url:               https://https://www.linkedin.com/in/davideweon/
  email:             davideweon@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/eunchanity

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
