title: Hi! I'm David Weon
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ":title/"
baseurl: "/eunchanity.github.io" # the subpath of your site, e.g. /blog
url: "eunchanity.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: David Weon # add your name
author-img: david-weon.jpeg # add your photo
about-author: A data scientist who aims to ask the <b> right questions </b> and loves to <b> craft stories</b> # add description
# social-twitter: # add your Twitter handle
# social-facebook: # add your Facebook handle
social-github: eunchanity # add your Github handle
social-linkedin: davideweon #add your Linkedin handle
social-email: davideweon@gmail.com # add your Email address

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
